config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:create, :new, :show]
  resource :session, only: [:new, :create, :destroy]

  #resources :band, only: [:show, :update, :destroy, :edit, :new]
  resources :bands, only: [:index, :create, :new, :update, :destroy, :edit, :new] do
    resources :albums, only: [:new], on: :member
  end

  resources :albums, only: [:create, :edit, :show, :update, :destroy] do
    resources :tracks, only: [:new]
  end

  resources :tracks, only: [:create, :edit, :show, :update, :destroy]

end

app/models/album.rb
class Album < ActiveRecord::Base
  validates :band_id, :name, :record_type, presence: true
  belongs_to :band, dependent: :destroy
  has_many :tracks, dependent: :destroy

end

app/models/band.rb
class Band < ActiveRecord::Base
  validates :name, presence: true

  has_many :albums, dependent: :destroy
  has_many :tracks,
    through: :albums,
    source: :tracks,
    dependent: :destroy

end

app/models/track.rb
class Track < ActiveRecord::Base
  validates :name, :song_type, presence: true
  belongs_to :album, dependent: :destroy
  has_one :band,
    through: :album,
    source: :band

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_reader :password
  validates :password_digest, :session_token, presence: true
  validates :email, presence: true, uniqueness: true
  after_initialize :ensure_session_token

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def reset_session_token!
    session_token = User.generate_session_token
  end

  def ensure_session_token
    session_token ||= User.generate_session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return user if user && user.password=password
    nil
  end

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

    def new
      @bands = Band.all
      render :new
    end

    def create
      @album = Album.create(album_params)
      if @album.save!
        redirect_to album_url(@album)
      else
        flash[:errors] = @album.errors.full_messages
        render :new
      end
    end

    def edit
      @bands = Band.all
      @album = Album.find(params[:id])
      render :update
    end

    def update
      album = Album.find(params[:id])
      if band.update_attributes(album_params)
        redirect_to album_url(album)
      else
        flash[:errors] = ["Album credentials missing"]
        render :update
      end
    end

    def destroy
      album = Album.find(params[:id])
      album.destroy
    end

    def show
      @album = Album.find(params[:id])
      render :show
    end

    private
    def album_params
      params.require(:album).permit(:name, :band_id, :record_type)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?, :log_in_user!, :reset_session_token!
  #before_action :require_login

  def current_user
    return nil if session[:session_token].nil?
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_in_user!(user)
    @current_user = user
    user.reset_session_token!
    session[:session_token] = user.session_token
  end

  def reset_session!
    session[:session_token] = nil
    @current_user = nil
  end

  def require_login
    unless logged_in?
      flash[:error] = "You must be logged in to access this section"
      redirect_to new_session_url
    end
  end

  def logout!
     current_user.reset_session_token! unless current_user.nil?
     session[:session_token] = nil
  end

end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def index
    @bands = Band.all
    render :index
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  def new
    render :new
  end

  def create
    @band = Band.new(band_params)
    if @band.save!
      redirect_to band_url(@band)
    else
      flash[:errors] = band.errors.full_messages
      render :new
    end
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def update
    band = Band.find(params[:id])
    if band.update_attributes(band_params)
      redirect_to band_url(band)
    else
      flash[:errors] = band.errors.full_messages
      render :edit
    end
  end

  def destroy
    band = Band.find(params[:id])
    band.destroy
  end


  private
  def band_params
    params.require(:band).permit(:name)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create
    @user = User.find_by_credentials(
      params[:user][:email],
      params[:user][:password]
    )

    if @user
      log_in_user!(@user)
      redirect_to user_url(@user.id)
    else
      flash[:errors] = ["Invalid User Credentials"]
      render :new
    end
  end

  def destroy
    logout!
    redirect_to bands_url
    # user.reset_session_token!
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  helper_method :current_user
  helper_method :logged_in?
  helper_method :log_in_user!

  def new
    render :new
  end

  def create
    user = User.new(user_params)
    user.session_token = user.ensure_session_token
    session[:session_token] = user.session_token

    if user.save!
      redirect_to user_url(user.id)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  def user_params
    params.require(:user).permit(:email, :password, :session_token)
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/albums/_form.html.erb
<form action="<%= album_url(params[:id]) %>" method="post">

  <select class="" name="album[band]">
      <option value="" disabled>--Select Band--</option>
      <% Band.all.each do |band| %>
        <% selected = band.id == @album.band_id %>
        <option <%= selected ? "selected" : "" %>
          value="<%= band.name %>">
          <%= band.name %>
        </option>
      <% end %>
  </select>
  <br><br>

  <input type="radio" name="album[record_type]" value="studio"> Studio<br>
  <input type="radio" name="album[record_type]" value="live"> Live<br>
  <br>

  Album Name: <input type="text" name="album[name]">
  <br><br>
  <%= button_to "Create new Album", band_url(params[:id]), method: :post %>

</form>

app/views/albums/index.html.erb
<h1>@band.name</h1>

<ul>
  <% band.tracks.each do |track| %>
    <li><%= track.name %></li>
  <% end %>
</ul>

app/views/albums/new.html.erb
<h1>Add a New Album</h1>

<%= render "form" %>

app/views/albums/show.html.erb
<h1><%= @album.name %></h1>

Band: <%= @album.band.name %> <br>
Record Type: <%= @album.record_type %>

<%= button_to "Update", album_url(@album), method: :patch %>
<%= button_to "Remove", album_url(@album), method: :delete %>

app/views/albums/update.html.erb
<h1>Update Album</h1>

<%= render "form" %>

app/views/bands/_form.html.erb
<form action="<%= bands_url %>" method="post">
  <label for="band_name">Band Name: </label>
  <input type="text" name="band[name]" id="band_name">
  <br><br>
  <%= button_to "Create New Band", bands_url, method: :post %>

</form>

app/views/bands/index.html.erb
<h1>All of My Favorite Bands!!!</h1>

<ul>
  <% @bands.each do |band| %>
    <li><a href="band_url(band)"><%= band.name %></a></li>
  <% end %>
</ul>

app/views/bands/new.html.erb
<h1>Add a New Band</h1>

<%= render "form" %>

app/views/bands/update.html.erb
<h1>Edit <%= @band.name %></h1>

<%= render "form" %>

app/views/layouts/application.html.erb
<% if logged_in? %>
  <% l_button = button_to "Logout", new_session_url, method: :delete %>
<% else %>
  <% l_button = button_to "Go to Login", new_session_url, method: :get %>
<% end %>

<% current_uri = request.env['PATH_INFO'] %>
<% login_page = (["/users/new", "/session/new", "/session", "/user"].include?(current_uri) ? true : false) %>

<!DOCTYPE html>
<html>
<head>
  <title>MusicApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= yield %>
  <%= l_button unless login_page %>

</body>
</html>

app/views/tracks/_form.html.erb
<form action="<%= tracks_url %>" method="post">
  <label for="track_name">Band Name: </label>
  <input type="text" name="track[name]" id="track_name">
  <br><br>
  <%= button_to "Create New Track", tracks_url, method: :post %>

</form>

app/views/tracks/index.html.erb
<h1>All of My Favorite Tracks!!!</h1>

<ul>
  <% @tracks.each do |track| %>
    <li><a href="track_url(track)"><%= track.name %></a></li>
  <% end %>
</ul>

app/views/tracks/new.html.erb
<h1>Add a New Track</h1>

<%= render "form" %>

app/views/tracks/update.html.erb
<h1>Edit <%= @track.name %></h1>

<%= render "form" %>

app/views/users/new.html.erb
<h1>Create a New Account</h1>

<form action="<%= users_url %>" method="post">
  Email: <input type="text" name="user[email]" value="">
  <br><br>
  Password: <input type="password" name="user[password]" value="">
  <br><br>
  <%= button_to "Create New Account", action: "create" %>

</form>

app/views/users/show.html.erb
<h1><%= @user.email %></h1>