solution/config/routes.rb
Musicapp::Application.routes.draw do
  root to: redirect("/bands")

  resource :session, only: [:create, :destroy, :new]
  resources :users, only: [:create, :new, :show] do
    get :activate, on: :collection
  end

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, only: [:create, :destroy, :edit, :show, :update] do
    resources :tracks, only: [:new]
  end

  resources :tracks, only: [:create, :destroy, :edit, :show, :update]

  resources :notes, only: [:create, :destroy]
end

solution/app/models/album.rb
class Album < ActiveRecord::Base
  belongs_to :band
  has_many :tracks, dependent: :destroy

  # can't use presence validation with boolean field
  validates :band, :name, :year, presence: true
  validates :live, inclusion: { in: [true, false] }
  validates :name, uniqueness: { scope: :band_id }
  validates :year, numericality: { minimum: 1900, maximum: 9000 }
end

solution/app/models/band.rb
class Band < ActiveRecord::Base
  has_many :albums, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

solution/app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :user
  belongs_to :track

  validates :content, :track_id, :user_id, presence: true
end

solution/app/models/track.rb
class Track < ActiveRecord::Base
  belongs_to :album
  has_one :band, through: :album, source: :band
  has_many :notes, dependent: :destroy

  validates :album, :lyrics, :name, :ord, presence: true

  # can't use presence validation with boolean field
  validates :bonus, inclusion: { in: [true, false] }
  validates :ord, uniqueness: { scope: :album_id }
end

solution/app/models/user.rb
# Monkey-patch ActiveRecord::Base to have a cool unique token method!
class ActiveRecord::Base
  def generate_unique_token_for_field(field)
    token = SecureRandom.base64(16)
    
    while self.class.exists?(field => token)
      token = SecureRandom.base64(16)
    end
    
    token
  end
end

class User < ActiveRecord::Base
  after_initialize :ensure_session_token
  after_initialize :set_activation_token

  validates :activation_token, :email, :session_token, uniqueness: true
  validates(
    :activation_token,
    :email,
    :password_digest,
    :session_token,
    presence: true
  )

  def self.find_by_credentials(email, password)
    user = User.find_by_email(email)

    user && user.is_password?(password) ? user : nil
  end

  def set_activation_token
    self.activation_token =
      generate_unique_token_for_field(:activation_token)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password).to_s
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token!
    self.session_token = generate_unique_token_for_field(:session_token)
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= generate_unique_token_for_field(:session_token)
  end

  def activate!
    self.update_attribute(:activated, true)
  end
end

solution/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :require_user!

  def create
    @album = Album.new(album_params)

    if @album.save
      redirect_to album_url(@album)
    else
      @band = @album.band
      render :new
    end
  end

  def destroy
    @album = Album.find(params[:id])
    @album.destroy
    redirect_to band_url(@album.band_id)
  end

  def edit
    @album = Album.find(params[:id])
    render :edit
  end

  def new
    @band = Band.find(params[:band_id])
    @album = Album.new(band_id: params[:band_id])
    render :new
  end

  def show
    @album = Album.find(params[:id])
    render :show
  end

  def update
    @album = Album.find(params[:id])

    if @album.update(album_params)
      redirect_to album_url(@album)
    else
      render :edit
    end
  end

  private
  def album_params
    params.require(:album).permit(:band_id, :live, :name, :year)
  end
end

solution/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :current_user_id, :logged_in?

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def current_user_id
    current_user ? current_user.id : nil
  end

  def logged_in?
    !!current_user
  end

  def login_user!(user)
    session[:session_token] = user.reset_session_token!
  end

  def require_user!
    redirect_to new_session_url if current_user.nil?
  end
end

solution/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :require_user!

  def create
    @band = Band.new(band_params)

    if @band.save
      redirect_to band_url(@band)
    else
      render :new
    end
  end

  def destroy
    @band = Band.find(params[:id])
    @band.destroy
    redirect_to bands_url
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def index
    @bands = Band.all
    render :index
  end

  def new
    @band = Band.new
    render :new
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  def update
    @band = Band.find(params[:id])
    if @band.update(band_params)
      redirect_to band_url(@band)
    else
      render :edit
    end
  end

  private
  def band_params
    params.require(:band).permit(:name)
  end
end

solution/app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :require_user!

  def create
    @note = Note.new(note_params)
    @note.user_id = current_user.id
    @note.save

    redirect_to track_url(@note.track_id)
  end

  def destroy
    @note = Note.find(params[:id])
    if @note.user_id != current_user_id
      render text: "Can only destroy your own note", status: :forbidden
    else
      @note.destroy
      redirect_to track_url(@note.track_id)
    end
  end

  private
  def note_params
    params.require(:note).permit(:content, :track_id)
  end
end

solution/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by_credentials(
      params[:user][:email],
      params[:user][:password]
    )

    if user.nil?
      render :new

    # Notice we have User#activated? even though we didn't define it!
    # Rails gives you this method for free because it matches a column name.
    elsif !user.activated?
      redirect_to root_url, alert: "You must activate your account first! Check your email."
    else
      login_user!(user)
      redirect_to root_url
    end
  end

  def destroy
    current_user.reset_session_token!
    session[:session_token] = nil

    redirect_to new_session_url
  end

  def new
    render :new
  end
end

solution/app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :require_user!

  def create
    @track = Track.new(track_params)

    if @track.save
      redirect_to track_url(@track)
    else
      @album = @track.album
      render :new
    end
  end

  def destroy
    @track = Track.find(params[:id])
    @track.destroy
    redirect_to album_url(@track.album_id)
  end

  def edit
    @track = Track.find(params[:id])
    render :edit
  end

  def new
    @album = Album.find(params[:album_id])
    @track = Track.new(album_id: params[:album_id])
    render :new
  end

  def show
    @track = Track.find(params[:id])
    render :show
  end

  def update
    @track = Track.find(params[:id])
    if @track.update(track_params)
      redirect_to track_url(@track)
    else
      render :edit
    end
  end

  private
  def track_params
    params.require(:track).permit(:album_id, :bonus, :lyrics, :name, :ord)
  end
end

solution/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    render :show
  end

  def create
    @user = User.new(user_params)

    if @user.save
      UserMailer.activation_email(@user).deliver!
      flash[:notice] =
        "Successfully created your account! Check your inbox for an activation email."
      redirect_to root_url
    else
      render :new
    end
  end

  def new
    @user = User.new
    render :new
  end

  def activate
    @user = User.find_by_activation_token(params[:activation_token])
    @user.activate!
    login_user!(@user)
    flash[:notice] = "Successfully activated your account!"
    redirect_to root_url
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

solution/app/helpers/application_helper.rb
module ApplicationHelper
  def ugly_lyrics(lyrics)
    formatted_lyrics = ""
    lyrics.lines.each do |line|
      formatted_lyrics << "&#9835; #{h(line)}"
    end

    "<pre>#{formatted_lyrics}</pre>".html_safe
  end
end

solution/app/views/albums/_form.html.erb
<% action_url = album.persisted? ? album_url(album) : albums_url %>
<% http_method = album.persisted? ? "PATCH" : "POST" %>
<% button_text = album.persisted? ? "Update Album!" : "Create Album!" %>

<% if !album.errors.full_messages.empty? %>
<ul>
  <% album.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

<form action="<%= action_url %>" method="POST">
  <input type="hidden" name="_method" value="<%= http_method %>">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <label>Name
    <input type="text" name="album[name]" value="<%= album.name %>">
  </label>
  <br>

  <label>Band
    <select name="album[band_id]">
        <% Band.all.each do |band| %>
            <option
                <%= "selected" if album.band_id == band.id %>
                value="<%= band.id %>">
                <%= band.name %>
            </option>
        <% end %>
    </select>
  </label>
  <br>

  <input
    type="radio"
    name="album[live]"
    value="t"
    id="album_live_t"
    <%= "checked" if album.live %>>
  <label for="album_live_t">Live</label>

  <input
    type="radio"
    name="album[live]"
    value="f"
    id="album_live_f"
    <%= "checked" if !album.live %>>
  <label for="album_live_f">Studio</label>
  <br>

  <label>Year
    <input type="number" name="album[year]" value="<%= album.year %>">
  </label>
  <br>

  <input type="submit" value="<%= button_text %>">
</form>

solution/app/views/albums/edit.html.erb
<h1>Edit <%= @album.name %></h1>

<%= render "form", album: @album %>

solution/app/views/albums/new.html.erb
<h1>New <%= @band.name %> Album!</h1>

<%= render "form", album: @album %>

solution/app/views/albums/show.html.erb
<h1><%= @album.name %></h1>

<ul>
  <% @album.tracks.each do |track| %>
    <li><%= link_to track.name, track_url(track) %></li>
  <% end %>
</ul>

<h4>Links</h4>
<ul>
  <li><%= link_to "New track", new_album_track_url(@album) %></li>
  <li><%= link_to "Edit Album", edit_album_url(@album) %></li>
  <li><%= link_to "Destroy Album", album_url(@album), method: :delete %></li>
  <li><%= link_to @album.band.name, band_url(@album.band) %></li>
</ul>

solution/app/views/bands/_form.html.erb
<% action_url = band.persisted? ? band_url(band) : bands_url %>
<% http_method = band.persisted? ? "PATCH" : "POST" %>

<% if !band.errors.full_messages.empty? %>
<ul>
  <% band.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

<form action="<%= action_url %>" method="POST">
  <input type="hidden" name="_method" value="<%= http_method %>">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <label>Name
  <input type="text" name="band[name]" value="<%= band.name %>">
  </label>
  <br>

  <input type="submit">
</form>

solution/app/views/bands/edit.html.erb
<h1>Edit <%= @band.name %></h1>

<%= render "form", band: @band %>

solution/app/views/bands/index.html.erb
<h1>Bands</h1>

<ul>
  <% @bands.each do |band| %>
    <li><%= link_to band.name, band_url(band) %></li>
  <% end %>
</ul>

<%= link_to "New band", new_band_url %>

solution/app/views/bands/new.html.erb
<h1>New Band!</h1>

<%= render "form", band: @band %>

solution/app/views/bands/show.html.erb
<h1><%= @band.name %></h1>

<ul>
  <% @band.albums.each do |album| %>
    <li><%= link_to album.name, album_url(album) %></li>
  <% end %>
</ul>

<h4>Links</h4>
<ul>
  <li><%= link_to "New album", new_band_album_url(@band) %></li>
  <li><%= link_to "Edit Band", edit_band_url(@band) %></li>
  <li><%= link_to "Delete Band", band_url(@band), method: :delete, class: 'btn' %></li>
  <li><%= link_to "All bands", bands_url %></li>
</ul>

solution/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Music App</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if logged_in? %>
  <p>Logged in as: <%= current_user.email %></p>
  <%= button_to "Sign Out", session_url, method: :delete %>
<% end %>

<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>

<%= yield %>

</body>
</html>

solution/app/views/note/_form.html.erb
<h2>New Note</h2>

<form action="<%= notes_url %>" method="POST">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <input type="hidden" name="note[track_id]" value="<%= track.id %>">

  <label for="note_content">Content</label>
  <br>

  <textarea id="note_content" name="note[content]"></textarea>
  <br>

  <input type="submit">
</form>

solution/app/views/note/_note.html.erb
<pre><%= note.content %></pre>
<p>Authored by: <%= note.user.email %></p>

<% if note.user_id == current_user_id %>
  <%= button_to "Destroy note!", note_url(note), method: :delete %>
<% end %>

solution/app/views/tracks/_form.html.erb
<% action_url = track.persisted? ? track_url(track) : tracks_url %>
<% http_method = track.persisted? ? "PATCH" : "POST" %>


<% if !track.errors.full_messages.empty? %>
<ul>
  <% track.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

<form action="<%= action_url %>" method="POST" %>
  <input type="hidden" name="_method" value="<%= http_method %>">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <input type="text" name="track[name]" value="<%= track.name %>">
  <br>

<label>Album
  <select name="track[album_id]">
    <% Album.all.each do |album| %>
      <option
        <%= "selected" if track.album_id == album.id %>
        value="<%= album.id %>">
          <%= album.name %>
      </option>
    <% end %>
  </select>
</label>
<br>

  <input type="number" name="track[ord]" value="<%= track.ord %>">
  <br>

  <input
    type="radio"
    name="track[bonus]"
    value="f"
    id="track_bonus_f"
    <%= "checked" if !track.bonus %>>
  <label for="track_bonus_f">Standard</label>
  <br>
  <input
    type="radio"
    name="track[bonus]"
    value="t"
    id="track_bonus_t"
    <%= "checked" if track.bonus %>>
  <label for="track_bonus_t">Bonus</label>
  <br>

  <label for="track_lyrics">Lyrics</label>
  <textarea id="track_lyrics" name="track[lyrics]"><%= track.lyrics %></textarea>
  <br>

  <input type="submit">
</form>

solution/app/views/tracks/edit.html.erb
<h1>Edit <%= @track.name %></h1>

<%= render "form", track: @track %>

solution/app/views/tracks/new.html.erb
<h1>New <%= @album.name %> Track</h1>

<%= render "form", track: @track %>

solution/app/views/tracks/show.html.erb
<h1><%= @track.name %></h1>

<%= ugly_lyrics(@track.lyrics) %>

<% @track.notes.each do |note| %>
  <%= render "note/note", note: note %>
<% end %>

<%= render "note/form", track: @track %>

<h4>Links</h4>
<ul>
  <li><%= link_to "Edit Track", edit_track_url(@track) %></li>
  <li><%= link_to "Delete Track", track_url(@track), method: :delete %></li>
  <li><%= link_to @track.album.name, album_url(@track.album) %></li>
</ul>